--- # demonstrates handlers

- hosts: webservers
  become: true
  handlers:
    - name: "add new user configuration"
      file:
        path: /tmp/user.conf
        state: touch
      listen: "update web services"  # listen!
    - name: "restart apache2"
      service:
        name: apache2
        state: restarted
      listen: "update web services"  # listen!
  tasks:
    - name: "install Apache2 webserver"
      apt:
        name: apache2
        state: present
    - name: "apache2 webserver is started"
      service:
        name: apache2
        state: started
    - name: "install libapache2-mod-python"
      apt:
        name: libapache2-mod-python
        state: present
      notify: "update web services"    # now a composite handler
    - name: "install libapache2-mod-wsgi-py3"
      apt:
        name: libapache2-mod-wsgi-py3
        state: present
      notify: "update web services"
