--- # nodejs role tasks

- name: "set up nodejs key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: "set up nodejs repository"
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_17.x impish main"
    state: present
- name: "install nodejs setup"
  apt:
    name: nodejs
    state: latest