Vagrant.configure("2") do |config|
  #config.vm.box = "spox/ubuntu-arm"
  config.vm.box = "bytesguy/ubuntu-server-21.10-arm64"
  config.vm.box_version = "1.0.0"
  config.vm.provider :vmware_desktop do |vmware|
    vmware.vmx["ethernet0.pcislotnumber"] = "160"
    #vmware.gui = true
  end
end
